/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "HAL/Hal_RCC.h"
#include "core/CortexM4_core_Systick.h"
#include "HAL/Hal_GPIO.h"
#include "core/CortexM4_core_NVIC.h"
#include "HAL/Hal_ADC.h"

uint32_t GSystickCnt = 0;
uint8_t GUsartFlag 	 = 0;
uint32_t GLedOn = 0;
uint16_t Res = 0;

void Systick_Delay();
void GPIO_INT4_Input();

int main(void)
{
	ERR Status = HAL_OK;
	/* RCC configuration Structure */
	RCC_Config_t RCC_Config = {
			.MSTR_CLK_SRC = SW_CLK_PLLO,
			.PLL_SRC = PLL_HSE,
			.PLL_M = 25,
			.PLL_N = 168,
			.PLL_P = PLLP_2,
			.PLL_Q = PLLQ_4_S,
			.AHB_PRE = AHBDIV_1,
			.APB1_PRE = APB_AHB_2,
			.APB2_PRE = APB_AHB_1,
	};
	/*Systick Configuration Structure */
	SYSTICK_CFG SYS_Config = {
			.CLCK_DIV = SYS_CLK_8,
			.SYS_Callback =Systick_Delay,
	};
	/* GPIO struct */
	GPIO_InitStruct GPIO = { .Pin = GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3,
			.Speed = GPIO_Speed_2MHz,
			.mode = GPIO_MODE_OUTPUT_PP,
			.pull =GPIO_NOPULL,
	};
	GPIO_InitStruct GPIO2 = {
			.Pin = GPIO_PIN_5,
			.Speed = GPIO_Speed_2MHz,
			.mode = GPIO_MODE_IT_RISING,
			.pull = GPIO_NOPULL,
			.GPIO5_Callbck =GPIO_INT4_Input,
	};
	/* SystemClock Init */
	Status = HAL_RCC_Init(&RCC_Config);
	/* Systick Init */
	Status = HAL_SYSTICK_Init(&SYS_Config);
	/*GPIO Init */
	Status = HAL_GPIO_Init(GPIOA, &GPIO);
	Status = HAL_GPIO_Init(GPIOA, &GPIO2);
	/*Adc init */
	ADC_SConfig_t Adc={
			.APB_P   = ADC_APBP_8,
			.Allign  = LEFT_ALLIGNMENT,
			.Channel = ADC_IN4,
			.RES     = ADC_RES_12,
	};
	HAL_ADC_Init(&Adc);
	while(1)
	{
		if(GUsartFlag==1)
		{
			GUsartFlag=0;
			HAL_GPIO_TogglePin(GPIOA,GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);
		}
		Res=HAL_ADC_ResultBlocking(Adc.Allign,ADC_IN4);
	}
}

void Systick_Delay()
{
	static uint32_t sSystickTick = 0;
	sSystickTick++;
	if( sSystickTick == 499)
	{
		GUsartFlag = 1;
		sSystickTick=0;
	}
}

void GPIO_INT4_Input()
{
	GLedOn++;
}


