/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "HAL/Hal_RCC.h"
#include "core/CortexM4_core_Systick.h"
#include "HAL/Hal_GPIO.h"
#include "core/CortexM4_core_NVIC.h"

uint32_t GSystickCnt = 0;
uint8_t GUsartFlag 	 = 0;
uint32_t GLedOn = 0;

void Systick_Delay();
void GPIO_INT4_Input();

int main(void)
{
	uint32_t LAPB1_CLK = 0x00000000U;
	ERR Status = HAL_OK;
	/* RCC configuration Structure */
	RCC_Config_t RCC_Config={
			.MSTR_CLK_SRC = SW_CLK_PLLO,
			.PLL_SRC = PLL_HSE,
			.PLL_M = 25,
			.PLL_N = 168,
			.PLL_P = PLLP_2,
			.PLL_Q = PLLQ_4_S,
			.AHB_PRE = AHBDIV_1,
			.APB1_PRE = APB_AHB_2,
			.APB2_PRE = APB_AHB_1,
	};
	/*Systick Configuration Structure */
	SYSTICK_CFG SYS_Config ={
			.CLCK_DIV = SYS_CLK_8,
			.SYS_Callback = Systick_Delay,
	};
	/* GPIO struct */
	GPIO_InitStruct GPIO={
			.Pin = GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3,
			.Speed = GPIO_Speed_2MHz,
			.mode  = GPIO_MODE_OUTPUT_PP,
			.pull  = GPIO_NOPULL,
	};
	GPIO_InitStruct GPIO2={
			.Pin   = GPIO_PIN_5,
			.Speed = GPIO_Speed_2MHz,
			.mode  = GPIO_MODE_IT_RISING,
			.pull  = GPIO_NOPULL,
			.GPIO5_Callbck = GPIO_INT4_Input,
	};
    /* SystemClock Init */
	Status   = HAL_RCC_Init(&RCC_Config);
	/* APB1 Speed API */
	LAPB1_CLK = HAL_RCC_GET_APB1FREQ();
	/* Systick Init */
	Status   = HAL_SYSTICK_Init(&SYS_Config);
	/*GPIO Init */
	Status   = HAL_GPIO_Init(GPIOA , &GPIO );
	Status   = HAL_GPIO_Init(GPIOA , &GPIO2 );
	/*Enable USART interrupt */
//	NVIC_EnableIRQ(USART1_IRQ);
	/*Set interrupt as pending since no interrupts are requested other than the uart it will be fired*/
//	NVIC_SetPendingIRQ(USART1_IRQ);
	while(1)
	{
		if(GUsartFlag == 1)
		{
			HAL_GPIO_TogglePin(GPIOA , GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3);
			GUsartFlag = 0;
		}
	}
}


void Systick_Delay()
{
	static uint32_t sSystickTick = 0;
	sSystickTick++;
	if( sSystickTick == 499)
	{
		GUsartFlag = 1;
		sSystickTick=0;
	}
}

void GPIO_INT4_Input()
{
	GLedOn++;
}
